import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <link rel="manifest" href="/manifest.json" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className="text-3xl font-bold underline">Pokedex</span>
      {/* TODO: genarate favicons, and update manifest.json */}
    </>
  );
}
